export const DAY=86400000;
export function validDay(k){return typeof k==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(k)&&k>='1900-01-01'&&k<='2100-12-31'&&!Number.isNaN(date(k).getTime())&&dayKey(date(k),{rollover:'00:00'})===k}
export function validTime(k){return typeof k==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(k)}
export const empty=()=>({schemaVersion:1,activities:[],sessions:[],holidays:[],focusPeriods:[],timer:null,focus:null,reports:{},settings:{finish:'22:30',rollover:'04:00'}});
export function dayKey(t,settings){const d=new Date(t),[h,m]=settings.rollover.split(':').map(Number);if(d.getHours()*60+d.getMinutes()<h*60+m)d.setDate(d.getDate()-1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
export function date(k){return new Date(k+'T12:00:00')}
export function shift(k,n){const d=date(k);d.setDate(d.getDate()+n);return dayKey(d,{rollover:'00:00'})}
export function week(k){return shift(k,-(date(k).getDay()+6)%7)}
export function holiday(s,k){return s.holidays.some(x=>x.start<=k&&x.end>=k)}
export function minutes(s,id,k){return s.sessions.filter(x=>x.activityId===id&&x.day===k).reduce((n,x)=>n+x.minutes,0)}
export function credited(actual,a){return Math.min(actual,a.maximum)}
export function touched(actual,a){return actual>=a.minimum}
export function weekStats(s,a,k){const w=week(k),days=Array.from({length:7},(_,i)=>shift(w,i)),available=days.filter(d=>!holiday(s,d));return {actual:days.reduce((n,d)=>n+minutes(s,a.id,d),0),credited:days.reduce((n,d)=>n+credited(minutes(s,a.id,d),a),0),touches:days.filter(d=>touched(minutes(s,a.id,d),a)).length,goal:a.weekly*available.reduce((n,d)=>n+(s.focusPeriods.some(f=>f.day===d&&f.activityId!==a.id)?focusAllowance(s,d):1),0)/7,touchGoal:Math.min(a.touches,available.length),available:available.length}}
export function spacing(s,a,k){const keys=[...new Set(s.sessions.filter(x=>x.activityId===a.id&&x.day<=k).map(x=>x.day))].sort();const valid=keys.filter(d=>touched(minutes(s,a.id,d),a)),last=valid.at(-1);let gap=0;if(last)for(let d=shift(last,1);d<=k;d=shift(d,1))if(!holiday(s,d)&&!s.focusPeriods.some(f=>f.day===d))gap++;const interval=Math.max(1,Math.floor(7/Math.max(1,a.touches)));return {last,gap,interval,state:!last?'recommended':gap>interval?'overdue':gap===interval?'due':gap===interval-1?'recommended':'steady'}}
export function focusAllowance(s,k){const [h,m]=s.settings.finish.split(':').map(Number),[rh,rm]=s.settings.rollover.split(':').map(Number);const start=date(k);start.setHours(rh,rm,0,0);const end=date(k);end.setHours(h,m,0,0);if(end<=start)end.setDate(end.getDate()+1);const intervals=s.focusPeriods.filter(f=>f.day===k).map(f=>[Math.max(start.getTime(),f.startedAt),Math.min(end.getTime(),f.endedAt)]).filter(([a,b])=>b>a).sort((a,b)=>a[0]-b[0]);let used=0,until=0;for(const [a,b] of intervals){used+=Math.max(0,b-Math.max(a,until));until=Math.max(until,b)}return Math.max(0,1-used/(end-start))}
export function activeOn(a,k,settings){return dayKey(a.createdAt,settings)<=k&&(!a.archived||(a.archivedSince&&k<dayKey(a.archivedSince,settings)))}
export function expectedToday(s,k){if(holiday(s,k)||s.focus)return [];return s.activities.filter(a=>activeOn(a,k,s.settings)).filter(a=>{const st=weekStats(s,a,k),sp=spacing(s,a,k),remaining=Array.from({length:7},(_,i)=>shift(week(k),i)).filter(d=>d>=k&&!holiday(s,d)).length;return a.importance==='Core'||minutes(s,a.id,k)>0||(['due','overdue','recommended'].includes(sp.state)&&st.touches<st.touchGoal)||(st.goal-st.credited>0&&(st.goal-st.credited)/Math.max(1,remaining)>=a.minimum)||(st.touchGoal-st.touches>=remaining&&remaining>0)})}
export function levels(s,k){const expected=expectedToday(s,k),core=expected.filter(a=>a.importance==='Core'),important=expected.filter(a=>a.importance==='Important');const factor=focusAllowance(s,k);const req=(arr,type)=>arr.map(a=>({id:a.id,required:a[type]*factor}));const combine=(...arr)=>arr.flat();const stages=[{name:'CORE',req:req(core,'minimum')},{name:'CORE+',req:combine(req(core,'minimum'),req(important,'minimum'))},{name:'CORE++',req:combine(req(core,'target'),req(important,'minimum'))},{name:'ALL',req:combine(req(core,'target'),req(important,'minimum'),req(expected.filter(a=>a.importance==='Normal'),'minimum'))},{name:'ALL+',req:req(expected,'target')}];let level='ZERO DAY',next=null;for(const stage of stages){stage.total=stage.req.reduce((n,r)=>n+r.required,0);stage.done=stage.req.reduce((n,r)=>n+Math.min(r.required,minutes(s,r.id,k)),0);stage.remaining=stage.total-stage.done;if(core.length&&stage.remaining<=0)level=stage.name;else {next=stage;break}}return {level,next,expected,coreRemaining:core.reduce((n,a)=>n+Math.max(0,a.minimum*factor-minutes(s,a.id,k)),0),coreActual:s.activities.filter(a=>a.importance==='Core').reduce((n,a)=>n+minutes(s,a.id,k),0)}}
export function finishRemaining(s,k,now=Date.now()){const [h,m]=s.settings.finish.split(':').map(Number),[rh,rm]=s.settings.rollover.split(':').map(Number);const d=date(k);d.setHours(h,m,0,0);if(h*60+m<rh*60+rm)d.setDate(d.getDate()+1);return Math.max(0,(d.getTime()-now)/60000)}
export function salvage(s,k,now){const l=levels(s,k);return {prominent:!s.focus&&!holiday(s,k)&&l.coreRemaining>45&&l.coreRemaining>finishRemaining(s,k,now),secured:l.coreActual>=45,remaining:Math.max(0,45-l.coreActual)}}
export function recommend(s,k){if(s.focus)return [];const l=levels(s,k);return s.activities.filter(a=>!a.archived&&minutes(s,a.id,k)<a.maximum).map(a=>{const n=minutes(s,a.id,k),sp=spacing(s,a,k),st=weekStats(s,a,k),needed=l.next?.req.find(r=>r.id===a.id);const score=({Core:3000,Important:2000,Normal:1000}[a.importance])+({overdue:400,due:300,recommended:150,steady:0}[sp.state])+(n<a.minimum?200:n<a.target?100:0)+(needed&&needed.required>n?80:0)+Math.max(0,st.goal-st.credited)/Math.max(1,st.goal)*50;return {a,score,duration:Math.min(a.maximum-n,Math.max(1,(n<a.minimum?a.minimum:a.target)-n)),reasons:[`${a.importance} activity`,sp.state==='steady'?'Continuity is on track':`Touch ${sp.state}`,n<a.minimum?`${Math.ceil(a.minimum-n)} min secures today's touch`:'Touch secured today',needed&&needed.required>n?`Moves you toward ${l.next.name}`:'Builds weekly progress']}}).sort((a,b)=>b.score-a.score||a.a.name.localeCompare(b.a.name))}
export function report(s,w){const days=Array.from({length:7},(_,i)=>shift(w,i)),activities=s.activities.map(a=>({...a,...weekStats(s,a,w),longestGap:Math.max(0,...days.filter(d=>d<=dayKey(Date.now(),s.settings)).map(d=>spacing(s,a,d).gap))}));return {week:w,total:activities.reduce((n,a)=>n+a.actual,0),activities,priority:Object.fromEntries(['Core','Important','Normal'].map(p=>[p,activities.filter(a=>a.importance===p).reduce((n,a)=>n+a.actual,0)])),days:days.map(day=>({day,level:day>dayKey(Date.now(),s.settings)?'UPCOMING':holiday(s,day)?'HOLIDAY':levels(s,day).level==='ZERO DAY'&&s.focusPeriods.some(f=>f.day===day)?'FOCUS / EXCUSED':levels(s,day).level==='ZERO DAY'&&salvage(s,day).secured?'SALVAGED':levels(s,day).level})),focus:s.focusPeriods.filter(f=>days.includes(f.day))}}
export function rolloverReports(s,k){const anchors=s.sessions.map(x=>x.day).concat(s.focusPeriods.map(x=>x.day),s.activities.map(a=>dayKey(a.createdAt||Date.now(),s.settings)));if(!anchors.length)return;const weeks=[];for(let w=week(anchors.sort()[0]);w<week(k);w=shift(w,7))weeks.push(w);for(const w of weeks)if(w<week(k))s.reports[w]=report(s,w)}
export function splitSegments(segments,settings){const perDay={};for(const seg of segments){let cursor=seg.start;while(cursor<seg.end){const k=dayKey(cursor,settings),next=date(shift(k,1)),[h,m]=settings.rollover.split(':').map(Number);next.setHours(h,m,0,0);const end=Math.min(seg.end,next.getTime());if(end<=cursor)throw Error('Invalid day boundary');perDay[k]=(perDay[k]||0)+(end-cursor)/60000;cursor=end}}return perDay}
export function elapsed(t,now=Date.now()){return t.accumulated+(t.runningSince?(now-t.runningSince)/60000:0)}
export function validate(s){
if(!s||s.schemaVersion!==1||!Array.isArray(s.activities)||!Array.isArray(s.sessions)||!Array.isArray(s.holidays)||!Array.isArray(s.focusPeriods)||!s.settings||!validTime(s.settings.finish)||!validTime(s.settings.rollover))throw Error('Invalid or unsupported backup');
const ids=new Set();for(const a of s.activities){if(typeof a.id!=='string'||!a.id||ids.has(a.id)||typeof a.name!=='string'||!a.name.trim()||!['Core','Important','Normal'].includes(a.importance)||![a.minimum,a.target,a.maximum,a.weekly,a.touches].every(Number.isFinite)||a.minimum<=0||a.target<a.minimum||a.maximum<a.target||a.weekly<0||!Number.isInteger(a.touches)||a.touches<0||a.touches>7||!Number.isFinite(a.createdAt)||!validDay(dayKey(a.createdAt,s.settings)))throw Error('Invalid activity');ids.add(a.id)}
const sessionIds=new Set();for(const x of s.sessions){if(!x.id||sessionIds.has(x.id)||!ids.has(x.activityId)||!Number.isFinite(x.minutes)||x.minutes<=0||!validDay(x.day)||typeof x.task!=='string'||!x.task.trim())throw Error('Invalid session');sessionIds.add(x.id)}
if(s.timer){const t=s.timer;if(!ids.has(t.activityId)||typeof t.task!=='string'||!t.task.trim()||!Array.isArray(t.segments)||!Number.isFinite(t.accumulated)||t.accumulated<0||(t.runningSince!==null&&!Number.isFinite(t.runningSince)))throw Error('Invalid timer');for(const g of t.segments)if(!Number.isFinite(g.start)||!Number.isFinite(g.end)||g.end<g.start)throw Error('Invalid timer segment')}
for(const h of s.holidays)if(!validDay(h.start)||!validDay(h.end)||h.end<h.start)throw Error('Invalid holiday');
for(const f of s.focusPeriods)if(!validDay(f.day)||!Number.isFinite(f.startedAt)||!Number.isFinite(f.endedAt)||f.endedAt<f.startedAt)throw Error('Invalid Focus period');
if(s.focus&&(!ids.has(s.focus.activityId)||!validDay(s.focus.day)||!Number.isFinite(s.focus.startedAt)))throw Error('Invalid Focus activity');
s.reports=s.reports&&typeof s.reports==='object'?s.reports:{};return s}

// Count each activity only up to its own weekly goal: surplus cannot cover another Core activity.
export function weeklyCoreProgress(s,k){return s.activities.filter(a=>!a.archived&&a.importance==='Core').reduce((sum,a)=>{const st=weekStats(s,a,k);return {done:sum.done+Math.min(st.credited,st.goal),goal:sum.goal+st.goal}}, {done:0,goal:0})}
